/*
NDE Automotive AI
Configuration Manager

Centralized configuration loader.
Allows automatic optimization via environment variables.
*/

const DEFAULT_CONFIG = {

  SEARCH_CACHE_TTL_MINUTES: 10,
  SEARCH_CACHE_MAX_SIZE: 1000,

  AUTO_LEARNING_INTERVAL_MINUTES: 10,
  RELEVANCE_OPTIMIZER_INTERVAL_MINUTES: 5,

  SHOPIFY_SYNC_INTERVAL_MINUTES: 30,

  ANALYTICS_SAMPLE_SIZE: 1000

};

let CONFIG = { ...DEFAULT_CONFIG };

export function loadConfig() {

  CONFIG.SEARCH_CACHE_TTL_MINUTES =
    parseInt(process.env.SEARCH_CACHE_TTL_MINUTES) ||
    DEFAULT_CONFIG.SEARCH_CACHE_TTL_MINUTES;

  CONFIG.SEARCH_CACHE_MAX_SIZE =
    parseInt(process.env.SEARCH_CACHE_MAX_SIZE) ||
    DEFAULT_CONFIG.SEARCH_CACHE_MAX_SIZE;

  CONFIG.AUTO_LEARNING_INTERVAL_MINUTES =
    parseInt(process.env.AUTO_LEARNING_INTERVAL_MINUTES) ||
    DEFAULT_CONFIG.AUTO_LEARNING_INTERVAL_MINUTES;

  CONFIG.RELEVANCE_OPTIMIZER_INTERVAL_MINUTES =
    parseInt(process.env.RELEVANCE_OPTIMIZER_INTERVAL_MINUTES) ||
    DEFAULT_CONFIG.RELEVANCE_OPTIMIZER_INTERVAL_MINUTES;

  CONFIG.SHOPIFY_SYNC_INTERVAL_MINUTES =
    parseInt(process.env.SHOPIFY_SYNC_INTERVAL_MINUTES) ||
    DEFAULT_CONFIG.SHOPIFY_SYNC_INTERVAL_MINUTES;

  CONFIG.ANALYTICS_SAMPLE_SIZE =
    parseInt(process.env.ANALYTICS_SAMPLE_SIZE) ||
    DEFAULT_CONFIG.ANALYTICS_SAMPLE_SIZE;

}

export function getConfig() {
  return CONFIG;
}
