const parts = [
"engine block",
"short block",
"long block",
"cylinder block",
"engine mount",
"engine bracket",
"engine support",
"oil sump",
"oil pan",
"dipstick tube",
"crank pulley",
"harmonic balancer",
"crank seal",
"cam gear",
"cam pulley",
"engine gasket kit",
"engine overhaul kit",
"engine bearing",
"main bearing",
"rod bearing",
"brake pad set",
"brake pad sensor",
"ceramic brake pad",
"semi metallic brake pad",
"brake rotor vented",
"brake rotor solid",
"brake caliper bracket",
"caliper piston",
"caliper seal kit",
"caliper slide pin",
"brake drum assembly",
"brake adjuster",
"brake spring kit",
"brake proportioning valve",
"brake pressure switch",
"brake hose front",
"brake hose rear",
"abs wheel sensor",
"abs pump",
"abs control module",
"engine air filter",
"panel air filter",
"sports air filter",
"performance air filter",
"cold air intake filter",
"oil filter cartridge",
"spin on oil filter",
"diesel fuel filter",
"petrol fuel filter",
"in line fuel filter",
"cabin pollen filter",
"ac pollen filter",
"activated carbon filter",
"engine breather filter",
"transmission filter",
"hydraulic filter",
"secondary air filter",
"air intake filter",
"turbo air filter",
"filter housing",
"radiator fan blade",
"radiator fan shroud",
"cooling fan relay",
"cooling fan resistor",
"coolant reservoir",
"coolant expansion tank",
"radiator mounting bracket",
"radiator drain plug",
"radiator support",
"thermostat housing",
"thermostat gasket",
"water pump pulley",
"heater core",
"heater hose",
"heater valve",
"coolant temperature switch",
"coolant level sensor",
"radiator guard",
"intercooler pipe",
"intercooler hose",
"shock absorber front",
"shock absorber rear",
"gas shock absorber",
"strut assembly",
"strut cartridge",
"strut bearing",
"coil spring front",
"coil spring rear",
"leaf spring shackle",
"leaf spring bush",
"control arm bush",
"lower control arm",
"upper control arm",
"ball joint upper",
"ball joint lower",
"sway bar link",
"stabilizer bush",
"suspension crossmember",
"suspension mount",
"suspension bracket",
"steering rack assembly",
"rack and pinion",
"power steering pump",
"power steering reservoir",
"power steering hose high pressure",
"power steering return hose",
"steering knuckle",
"steering column shaft",
"steering universal joint",
"steering wheel hub",
"steering wheel cover",
"tie rod inner",
"tie rod outer",
"rack boot",
"rack bellow",
"steering damper",
"steering coupler",
"steering lock",
"steering bracket",
"steering sensor",
"clutch disc",
"clutch pressure plate",
"clutch release bearing",
"clutch master cylinder",
"clutch slave cylinder",
"clutch cable",
"clutch fork",
"clutch pedal switch",
"flywheel bolt",
"dual mass flywheel",
"gear synchronizer",
"gear selector fork",
"gear shift lever",
"gear shift cable",
"gear knob cover",
"transmission pan",
"transmission mount bracket",
"automatic transmission filter",
"torque converter",
"gearbox seal",
"electric fuel pump",
"mechanical fuel pump",
"fuel injector nozzle",
"fuel injector seal",
"fuel injector rail",
"fuel pressure regulator",
"fuel return line",
"fuel delivery pipe",
"fuel tank strap",
"fuel tank cap",
"fuel tank sensor",
"fuel sending unit",
"fuel pump relay",
"fuel pump wiring",
"fuel vapor canister",
"charcoal canister",
"fuel filler neck",
"fuel tank gasket",
"fuel filter bracket",
"fuel hose connector",
"alternator pulley",
"alternator regulator",
"alternator brush",
"battery terminal",
"battery cable",
"battery hold down",
"main fuse",
"fuse holder",
"relay socket",
"wiring connector",
"ecu module",
"engine control module",
"body control module",
"door control module",
"sensor connector",
"wire harness clip",
"electrical terminal",
"electrical connector",
"ground cable",
"voltage regulator",
"led headlight bulb",
"halogen headlight bulb",
"xenon hid bulb",
"projector headlamp",
"tail lamp assembly",
"rear combination lamp",
"fog lamp housing",
"daytime running light module",
"indicator relay",
"turn signal bulb",
"corner light",
"reverse light bulb",
"license plate lamp",
"interior dome lamp",
"reading light",
"door courtesy light",
"glove box light",
"trunk light",
"map light",
"led strip light",
"front bumper cover",
"rear bumper cover",
"bumper reinforcement",
"bumper absorber",
"bumper mounting bracket",
"radiator grille",
"upper grille",
"lower grille",
"hood latch",
"hood hinge",
"hood strut",
"bonnet stay",
"fender liner",
"wheel arch trim",
"rocker panel",
"side skirt",
"quarter panel",
"trunk lid",
"tailgate panel",
"body clip",
"side mirror assembly",
"mirror indicator",
"mirror turn signal",
"mirror glass heated",
"mirror adjustment motor",
"mirror folding motor",
"mirror base plate",
"mirror mounting bracket",
"mirror trim",
"mirror housing",
"mirror shell",
"mirror actuator",
"mirror switch",
"mirror wiring",
"mirror gasket",
"mirror bracket",
"mirror cap",
"mirror signal lens",
"mirror hinge",
"mirror holder",
"front windshield glass",
"rear windshield glass",
"door window glass",
"quarter window glass",
"sunroof glass",
"window regulator cable",
"window regulator gear",
"window motor assembly",
"window switch panel",
"window channel",
"window weatherstrip",
"window molding",
"glass seal",
"glass adhesive",
"window clip",
"window guide rail",
"window roller",
"window regulator bracket",
"window lift arm",
"window stopper",
"dashboard panel",
"instrument cluster panel",
"center console",
"console lid",
"console cup holder",
"glove box lid",
"glove box hinge",
"interior door handle",
"door armrest",
"seat cushion",
"seat backrest",
"seat recliner",
"seat rail",
"seat adjustment lever",
"seat belt retractor",
"seat belt buckle",
"seat belt guide",
"carpet mat",
"floor insulation",
"sound deadening pad",
"wiper blade rubber",
"wiper blade frame",
"rear wiper blade",
"wiper arm front",
"wiper arm rear",
"wiper linkage",
"wiper motor assembly",
"wiper motor relay",
"washer pump motor",
"washer reservoir tank",
"washer fluid cap",
"washer nozzle jet",
"washer hose pipe",
"washer tee connector",
"washer filter",
"wiper pivot shaft",
"wiper mounting nut",
"wiper cover cap",
"wiper transmission",
"wiper bracket",
"exhaust manifold",
"exhaust gasket",
"exhaust flange",
"exhaust flex pipe",
"exhaust pipe center",
"exhaust muffler",
"rear muffler",
"exhaust resonator",
"catalytic converter",
"oxygen sensor upstream",
"oxygen sensor downstream",
"exhaust hanger",
"exhaust clamp",
"exhaust bracket",
"exhaust heat shield",
"tail pipe",
"silencer tip",
"exhaust mount rubber",
"exhaust shield bolt",
"exhaust flange bolt",
"car floor mat",
"rubber floor mat",
"trunk cargo tray",
"boot liner",
"sun visor extender",
"window sunshade",
"dashboard cover",
"seat cover leather",
"seat cover fabric",
"steering wheel cover leather",
"phone holder mount",
"dashboard organizer",
"car trash bin",
"door sill protector",
"door edge guard",
"car perfume diffuser",
"car cup holder extender",
"rear seat organizer",
"headrest pillow",
"neck cushion",
"engine bolt",
"engine stud",
"flange bolt",
"hex bolt",
"torx bolt",
"body clip fastener",
"plastic rivet",
"trim clip",
"panel fastener",
"bumper clip",
"push retainer",
"metal bracket",
"mounting stud",
"mounting nut",
"mounting washer",
"retaining ring",
"circlip",
"snap ring",
"locking nut",
"body screw",
"wheel bearing front",
"wheel bearing rear",
"hub bearing assembly",
"axle bearing",
"transmission bearing",
"input shaft bearing",
"output shaft bearing",
"differential bearing",
"carrier bearing",
"center support bearing",
"clutch release bearing",
"pilot bearing",
"idler pulley bearing",
"tensioner pulley bearing",
"alternator bearing",
"starter bearing",
"fan clutch bearing",
"steering column bearing",
"wheel hub bearing",
"roller bearing",
"wheel hub assembly",
"front hub assembly",
"rear hub assembly",
"hub flange",
"hub bolt",
"hub nut",
"hub cap",
"hub dust cover",
"hub carrier",
"hub knuckle",
"hub retaining ring",
"hub spacer",
"hub washer",
"hub stud",
"wheel stud",
"wheel bolt",
"wheel spacer",
"hub lock nut",
"hub grease cap",
"hub mounting plate",
"wheel hub assembly",
"front hub assembly",
"rear hub assembly",
"hub flange",
"hub bolt",
"hub nut",
"hub cap",
"hub dust cover",
"hub carrier",
"hub knuckle",
"hub retaining ring",
"hub spacer",
"hub washer",
"hub stud",
"wheel stud",
"wheel bolt",
"wheel spacer",
"hub lock nut",
"hub grease cap",
"hub mounting plate",
"differential case",
"differential gear",
"ring gear",
"pinion gear",
"pinion seal",
"differential gasket",
"differential carrier",
"differential housing",
"differential cover",
"differential mount",
"differential bearing kit",
"limited slip differential",
"differential bolt",
"differential spacer",
"differential washer",
"differential shaft",
"differential lock actuator",
"differential pin",
"differential shim",
"differential support bracket",
"serpentine belt",
"drive belt",
"fan belt",
"alternator belt",
"ac compressor belt",
"power steering belt",
"belt tensioner",
"belt tensioner pulley",
"idler pulley",
"belt guide pulley",
"belt adjuster",
"belt mounting bracket",
"belt cover",
"belt shield",
"belt retaining bolt",
"belt alignment pulley",
"belt tension spring",
"belt drive assembly",
"belt pulley bolt",
"belt locking clip",
"head gasket",
"valve cover gasket",
"intake manifold gasket",
"exhaust manifold gasket",
"oil pan gasket",
"timing cover gasket",
"water pump gasket",
"thermostat gasket",
"fuel pump gasket",
"throttle body gasket",
"egr gasket",
"turbo gasket",
"injector seal",
"o ring gasket",
"seal ring",
"rubber gasket",
"metal gasket",
"gasket kit engine",
"gasket seal kit",
"gasket mounting ring",
"oil seal crankshaft",
"camshaft oil seal",
"valve stem seal",
"axle oil seal",
"transmission oil seal",
"differential oil seal",
"wheel hub seal",
"bearing seal",
"steering rack seal",
"power steering seal",
"hydraulic seal",
"rubber seal ring",
"lip seal",
"shaft seal",
"seal washer",
"seal retainer",
"seal housing",
"seal cap",
"seal mounting plate",
"seal protector",
"turbocharger assembly",
"turbo cartridge",
"turbo actuator",
"turbo wastegate",
"turbo boost valve",
"turbo oil line",
"turbo oil return pipe",
"turbo intercooler pipe",
"turbo intake pipe",
"turbo outlet pipe",
"turbo mounting gasket",
"turbo heat shield",
"turbo bracket",
"turbo clamp",
"turbo pressure sensor",
"turbo compressor housing",
"turbo turbine housing",
"turbo boost hose",
"turbo flange",
"turbo mounting bolt",
"crankshaft position sensor",
"camshaft position sensor",
"mass air flow sensor",
"manifold pressure sensor",
"engine coolant sensor",
"intake air temperature sensor",
"throttle position sensor",
"vehicle speed sensor",
"wheel speed sensor",
"knock sensor",
"fuel pressure sensor",
"oil pressure sensor",
"brake pedal sensor",
"accelerator pedal sensor",
"steering angle sensor",
"yaw rate sensor",
"parking sensor rear",
"parking sensor front",
"rain sensor",
"light sensor",
"engine mount front",
"engine mount rear",
"engine mount left",
"engine mount right",
"transmission mount",
"gearbox mount",
"differential mount",
"radiator mount",
"exhaust mount",
"suspension mount",
"shock mount",
"strut mount bearing",
"control arm mount",
"subframe mount",
"body mount",
"crossmember mount",
"rubber mounting bush",
"mounting bracket",
"mounting plate",
"mounting cushion",
"door panel clip",
"bumper retainer clip",
"fender liner clip",
"hood insulation clip",
"grille mounting clip",
"trim panel clip",
"dashboard retaining clip",
"pillar trim clip",
"weatherstrip clip",
"rocker panel clip",
"wheel arch clip",
"underbody shield clip",
"splash guard clip",
"carpet clip fastener",
"interior trim clip",
"plastic push clip",
"nylon body clip",
"panel retainer clip",
"body moulding clip",
"quarter panel clip",
"side body moulding",
"door moulding trim",
"bumper moulding strip",
"roof drip moulding",
"window belt moulding",
"chrome body strip",
"side skirt moulding",
"wheel arch moulding",
"tailgate moulding",
"bonnet chrome trim",
"pillar garnish trim",
"door garnish moulding",
"roof edge trim",
"chrome window trim",
"rear hatch trim",
"bumper chrome garnish",
"side chrome strip",
"door chrome garnish",
"body styling trim",
"decorative moulding strip",
"side body moulding",
"door moulding trim",
"bumper moulding strip",
"roof drip moulding",
"window belt moulding",
"chrome body strip",
"side skirt moulding",
"wheel arch moulding",
"tailgate moulding",
"bonnet chrome trim",
"pillar garnish trim",
"door garnish moulding",
"roof edge trim",
"chrome window trim",
"rear hatch trim",
"bumper chrome garnish",
"side chrome strip",
"door chrome garnish",
"body styling trim",
"decorative moulding strip",
"driver seat frame",
"passenger seat frame",
"seat foam cushion",
"seat lumbar support",
"seat adjustment motor",
"seat height adjuster",
"seat track rail",
"seat slide rail",
"seat hinge bracket",
"seat reclining mechanism",
"seat back panel",
"seat plastic trim",
"rear seat latch",
"rear seat hinge",
"seat anchor bracket",
"seat mounting bolt",
"seat support bracket",
"seat cushion cover",
"seat frame bracket",
"seat support rail",
"door latch assembly",
"door lock actuator",
"door striker plate",
"door hinge upper",
"door hinge lower",
"door check strap",
"door opening cable",
"door release cable",
"door lock cylinder",
"door key barrel",
"door handle outer",
"door handle inner",
"door panel bracket",
"door trim mounting clip",
"door weather seal",
"door rubber seal",
"door window channel",
"door glass runner",
"door latch cable",
"door hinge pin",
"trunk latch assembly",
"trunk lock cylinder",
"trunk hinge bracket",
"trunk hinge support",
"trunk release cable",
"trunk release motor",
"trunk strut support",
"trunk lid support rod",
"trunk interior trim",
"trunk cargo hook",
"trunk floor board",
"trunk floor carpet",
"trunk latch striker",
"trunk rubber stopper",
"trunk weather seal",
"trunk opening switch",
"trunk lid reinforcement",
"trunk hinge bolt",
"trunk lock actuator",
"trunk latch bracket",
"engine under cover",
"engine splash shield",
"transmission under cover",
"fuel tank shield",
"rear floor shield",
"front underbody panel",
"aerodynamic under tray",
"underbody heat shield",
"floor protection plate",
"engine guard plate",
"transmission guard plate",
"fuel line protection cover",
"exhaust heat shield",
"rear axle shield",
"underbody mounting bracket",
"underbody support plate",
"plastic splash guard",
"chassis protection cover",
"underbody air deflector",
"underbody reinforcement plate",
"alloy wheel rim",
"steel wheel rim",
"wheel center cap",
"wheel lug nut",
"wheel lug bolt",
"wheel valve stem",
"tire pressure sensor",
"tpms sensor",
"tire valve cap",
"wheel balance weight",
"wheel hub ring",
"wheel locking nut",
"wheel lock key",
"spare wheel mount",
"spare wheel carrier",
"wheel rim protector",
"wheel trim cover",
"wheel decorative cover",
"wheel alignment shim",
"wheel spacer plate",
"car alarm system",
"alarm siren module",
"remote key fob",
"keyless entry module",
"immobilizer module",
"anti theft sensor",
"steering lock system",
"central locking module",
"door lock sensor",
"remote locking receiver",
"alarm control module",
"panic alarm switch",
"security relay",
"vehicle tracking module",
"gps tracking device",
"anti theft bracket",
"alarm wiring harness",
"security control unit",
"remote unlock actuator",
"security antenna",
"navigation head unit",
"gps antenna module",
"touchscreen display unit",
"multimedia control unit",
"car radio tuner",
"bluetooth module",
"usb media interface",
"aux audio interface",
"navigation control panel",
"navigation display screen",
"audio amplifier module",
"speaker component set",
"door speaker unit",
"subwoofer speaker",
"tweeter speaker",
"navigation sd card slot",
"radio antenna base",
"radio antenna mast",
"multimedia wiring harness",
"infotainment control module",
"adaptive cruise radar",
"forward collision sensor",
"lane departure camera",
"lane assist sensor",
"blind spot radar",
"rear cross traffic sensor",
"driver monitoring camera",
"front radar module",
"rear radar module",
"adas control module",
"parking assist controller",
"surround view camera",
"front camera module",
"rear view camera",
"side view camera",
"adas wiring harness",
"lane keeping actuator",
"distance sensor module",
"collision avoidance radar",
"traffic sign recognition camera",
"hybrid battery pack",
"hybrid battery module",
"hybrid battery cooling fan",
"hybrid battery controller",
"hybrid power inverter",
"hybrid converter unit",
"hybrid motor generator",
"hybrid power control module",
"hybrid battery relay",
"hybrid battery sensor",
"hybrid cooling duct",
"hybrid battery cable",
"hybrid battery terminal",
"hybrid motor housing",
"hybrid inverter coolant pump",
"hybrid system wiring",
"hybrid battery cover",
"hybrid battery bracket",
"hybrid battery mounting frame",
"hybrid battery insulation plate",
"electric drive motor",
"electric motor controller",
"ev battery pack",
"ev battery module",
"ev battery cooling plate",
"ev inverter module",
"ev onboard charger",
"ev charging port",
"ev charging socket",
"ev battery management system",
"ev high voltage cable",
"ev power distribution unit",
"ev dc converter",
"ev motor mount",
"ev motor shaft",
"ev cooling pump",
"ev thermal management module",
"ev battery housing",
"ev charging controller",
"ev insulation monitor",
"driver airbag module",
"passenger airbag module",
"side curtain airbag",
"knee airbag module",
"airbag control unit",
"airbag crash sensor",
"airbag clock spring",
"airbag wiring harness",
"airbag mounting bracket",
"airbag inflator module",
"airbag deployment sensor",
"airbag diagnostic module",
"airbag steering connector",
"airbag safety module",
"airbag sensor bracket",
"airbag mounting bolt",
"airbag connector plug",
"airbag crash module",
"airbag harness connector",
"airbag system relay",
"heater core assembly",
"heater blower motor",
"heater blower resistor",
"heater control valve",
"heater temperature actuator",
"heater air duct",
"heater vent grille",
"heater control panel",
"heater fan switch",
"heater air outlet",
"heater air inlet duct",
"heater coolant hose",
"heater water valve",
"heater cable control",
"heater dashboard vent",
"heater air mixer door",
"heater airflow actuator",
"heater fan relay",
"heater blower housing",
"heater filter housing",
"dashboard trim panel",
"center console trim",
"door interior trim",
"pillar trim cover",
"roof trim liner",
"kick panel trim",
"lower dash trim",
"instrument panel trim",
"steering column trim",
"seat side trim",
"console side trim",
"rear pillar trim",
"cargo area trim",
"trunk side trim",
"floor trim cover",
"console bezel trim",
"audio panel trim",
"climate control trim",
"window switch trim",
"interior garnish trim",
"roof rail assembly",
"roof rack cross bar",
"roof antenna module",
"roof antenna mast",
"roof antenna base",
"roof weather seal",
"sunroof motor",
"sunroof control module",
"sunroof track rail",
"sunroof wind deflector",
"sunroof glass panel",
"sunroof seal gasket",
"sunroof drain hose",
"sunroof switch",
"sunroof cable drive",
"sunroof shade curtain",
"sunroof mounting bracket",
"roof reinforcement panel",
"roof lining clip",
"roof trim moulding",
"audio head unit",
"car stereo receiver",
"audio amplifier",
"audio control module",
"speaker mounting bracket",
"door speaker grille",
"woofer speaker",
"subwoofer enclosure",
"speaker wiring harness",
"audio antenna cable",
"audio control knob",
"volume control switch",
"steering audio switch",
"multimedia interface module",
"sound processor module",
"audio equalizer unit",
"speaker crossover network",
"audio fuse module",
"audio connector socket",
"speaker mounting ring",
"climate control module",
"climate control panel",
"climate temperature sensor",
"climate air mix actuator",
"climate blower controller",
"climate air vent",
"climate control knob",
"climate control switch",
"climate air distribution motor",
"climate control wiring harness",
"climate control display",
"climate recirculation actuator",
"climate fan speed resistor",
"climate air outlet vent",
"climate evaporator sensor",
"climate heater blend door",
"climate duct connector",
"climate temperature dial",
"climate control bracket",
"climate control circuit board",
"evap purge valve",
"evap canister valve",
"evap leak detection pump",
"evap vent valve",
"evap vapor hose",
"evap charcoal canister",
"evap purge hose",
"fuel vapor sensor",
"fuel tank pressure sensor",
"evap system filter",
"emission control valve",
"emission sensor module",
"exhaust gas recirculation valve",
"egr cooler",
"egr control solenoid",
"egr pipe assembly",
"egr temperature sensor",
"egr mounting gasket",
"emission control relay",
"emission vacuum hose",
"engine rebuild kit",
"engine overhaul gasket set",
"piston ring set",
"connecting rod",
"connecting rod bolt",
"connecting rod bushing",
"engine valve spring",
"engine valve guide",
"engine valve lifter",
"hydraulic valve lifter",
"engine timing gear",
"engine camshaft seal",
"engine crankshaft seal rear",
"engine crankshaft seal front",
"engine oil pickup tube",
"engine oil pickup screen",
"engine oil pressure relief valve",
"engine breather hose",
"engine breather valve",
"engine vacuum hose",
"air intake hose",
"air intake duct",
"air cleaner housing",
"air cleaner lid",
"air cleaner snorkel",
"intake manifold runner",
"intake manifold bolt",
"intake manifold spacer",
"intake air resonator",
"air intake temperature sensor",
"intake air control valve",
"intake manifold pressure hose",
"intake manifold support bracket",
"intake air silencer",
"intake throttle cable",
"intake vacuum chamber",
"intake airflow guide",
"intake filter box",
"intake duct clamp",
"intake air boot",
"air intake hose",
"air intake duct",
"air cleaner housing",
"air cleaner lid",
"air cleaner snorkel",
"intake manifold runner",
"intake manifold bolt",
"intake manifold spacer",
"intake air resonator",
"air intake temperature sensor",
"intake air control valve",
"intake manifold pressure hose",
"intake manifold support bracket",
"intake air silencer",
"intake throttle cable",
"intake vacuum chamber",
"intake airflow guide",
"intake filter box",
"intake duct clamp",
"intake air boot",
"brake master cylinder reservoir",
"brake master cylinder cap",
"brake pedal push rod",
"brake pedal return spring",
"brake pedal bracket",
"brake pedal position sensor",
"brake hydraulic modulator",
"brake distribution block",
"brake pressure regulator valve",
"brake fluid level switch",
"brake hydraulic pipe",
"brake pipe connector",
"brake pipe mounting clip",
"brake pressure sensor",
"brake fluid reservoir hose",
"brake vacuum hose",
"brake pedal rubber pad",
"brake pedal stopper",
"brake booster vacuum check valve",
"brake booster mounting bracket",
"propeller shaft center joint",
"propeller shaft yoke",
"propeller shaft flange",
"propeller shaft coupling",
"driveshaft universal joint",
"driveshaft slip joint",
"driveshaft mounting flange",
"driveshaft support bracket",
"driveshaft balancing weight",
"driveshaft coupling bolt",
"driveshaft rubber coupling",
"rear axle differential flange",
"front axle coupling joint",
"driveshaft retaining clip",
"driveshaft dust shield",
"driveshaft bearing support",
"driveshaft mounting plate",
"driveshaft alignment shim",
"driveshaft locking ring",
"driveshaft spacer washer",
"engine oil temperature sensor",
"engine coolant level sensor",
"engine idle air sensor",
"engine load sensor",
"engine vibration sensor",
"engine exhaust temperature sensor",
"engine boost pressure sensor",
"engine intake vacuum sensor",
"engine fuel temperature sensor",
"engine cam timing sensor",
"engine detonation sensor",
"engine throttle angle sensor",
"engine airflow pressure sensor",
"engine idle control switch",
"engine rpm sensor",
"engine cylinder pressure sensor",
"engine oil level sensor",
"engine coolant pressure sensor",
"engine idle feedback sensor",
"engine thermal switch",
"engine oil temperature sensor",
"engine coolant level sensor",
"engine idle air sensor",
"engine load sensor",
"engine vibration sensor",
"engine exhaust temperature sensor",
"engine boost pressure sensor",
"engine intake vacuum sensor",
"engine fuel temperature sensor",
"engine cam timing sensor",
"engine detonation sensor",
"engine throttle angle sensor",
"engine airflow pressure sensor",
"engine idle control switch",
"engine rpm sensor",
"engine cylinder pressure sensor",
"engine oil level sensor",
"engine coolant pressure sensor",
"engine idle feedback sensor",
"engine thermal switch",
"coolant bypass hose",
"coolant thermostat cover",
"coolant pipe connector",
"coolant outlet flange",
"coolant inlet flange",
"coolant circulation pump",
"coolant hose clamp",
"coolant hose connector",
"coolant pipe mounting bracket",
"coolant radiator shroud",
"coolant radiator frame",
"coolant radiator mount bracket",
"coolant expansion tank cap",
"coolant return pipe",
"coolant heater pipe",
"coolant bleed valve",
"coolant temperature switch",
"coolant sensor connector",
"coolant hose support clip",
"coolant pipe gasket",
"front cross member",
"rear cross member",
"engine subframe",
"suspension subframe",
"radiator support panel",
"bumper reinforcement beam",
"front crash bar",
"rear crash bar",
"frame rail extension",
"frame rail bracket",
"chassis reinforcement plate",
"floor support beam",
"pillar reinforcement plate",
"door impact beam",
"rear body panel",
"front apron panel",
"wheel well reinforcement",
"chassis mounting bracket",
"body frame connector",
"structural support bracket",
"oil drain plug",
"oil drain plug washer",
"engine oil filler cap",
"engine oil filler neck",
"engine oil dipstick handle",
"engine oil dipstick tube seal",
"radiator coolant cap",
"coolant overflow hose",
"coolant reservoir bracket",
"battery terminal clamp",
"battery hold down bracket",
"battery insulation cover",
"battery terminal protector",
"fuse box cover",
"fuse puller tool",
"relay mounting bracket",
"relay holder clip",
"diagnostic obd connector",
"diagnostic port cover",
"service interval reset switch",
"high flow engine air filter",
"heavy duty oil filter element",
"long life cabin air filter",
"engine breather filter element",
"secondary fuel filter element",
"primary diesel fuel filter",
"fuel water separator filter",
"inline petrol filter cartridge",
"engine oil bypass filter",
"engine oil cooler filter",
"cabin air micro filter",
"cabin pollen carbon filter",
"engine air filter housing seal",
"air filter intake snorkel seal",
"engine oil filter housing cap",
"engine oil filter housing seal",
"fuel filter housing cover",
"fuel filter mounting clamp",
"air intake filter sealing ring",
"cabin filter mounting frame",
"hydraulic engine mount",
"engine torque mount",
"engine side mounting bracket",
"engine rear torque rod",
"engine mount support plate",
"engine mount cross bracket",
"engine mount insulator bush",
"engine mount cushion rubber",
"engine mounting frame bracket",
"engine stabilizer mount",
"engine mount retaining bolt",
"engine mount reinforcement plate",
"engine vibration damper mount",
"engine mount anchor plate",
"engine mount lower support",
"engine mount upper bracket",
"engine mount side support",
"engine mount stabilizer bracket",
"engine mount torque arm",
"engine mount isolation bushing",
"front radiator grille assembly",
"front grille chrome surround",
"front grille center trim",
"front grille honeycomb insert",
"front grille mesh insert",
"front grille emblem holder",
"front grille support frame",
"front grille mounting bracket",
"front grille retaining clip",
"front grille upper panel",
"front grille lower panel",
"front grille decorative strip",
"front grille chrome accent",
"front grille matte black insert",
"front grille mounting screw",
"front grille mounting tab",
"front grille protective guard",
"front grille airflow panel",
"front grille trim molding",
"front grille reinforcement frame",
"electric side mirror assembly",
"manual side mirror assembly",
"heated side mirror glass",
"auto folding side mirror",
"side mirror indicator lens",
"side mirror turn signal module",
"side mirror adjustment switch",
"side mirror motor actuator",
"side mirror base mounting plate",
"side mirror housing shell",
"side mirror frame support",
"side mirror glass backing plate",
"side mirror wiring connector",
"side mirror mounting gasket",
"side mirror hinge support",
"side mirror reinforcement bracket",
"side mirror outer cover cap",
"side mirror signal diffuser",
"side mirror pivot joint",
"side mirror mounting screw",
"front wheel arch liner",
"rear wheel arch liner",
"inner fender splash guard",
"front fender wheel cover",
"fender liner mounting bracket",
"fender liner push fastener",
"fender liner retaining clip",
"fender liner side extension",
"fender liner protective shield",
"fender liner mud protector",
"fender liner inner panel",
"fender liner support brace",
"fender liner reinforcement plate",
"fender liner attachment tab",
"fender liner plastic guard",
"fender liner air deflector",
"fender liner sealing strip",
"fender liner mounting bolt",
"fender liner retaining screw",
"fender liner support clip",
"chrome exterior door handle",
"painted exterior door handle",
"rear exterior door handle",
"front exterior door handle",
"keyless entry door handle",
"door handle pull lever",
"door handle base plate",
"door handle mounting bracket",
"door handle return spring",
"door handle pivot pin",
"door handle trim cover",
"door handle mounting screw",
"door handle lock cylinder housing",
"door handle support frame",
"door handle gasket seal",
"door handle latch linkage",
"door handle reinforcement bracket",
"door handle protective cover",
"door handle pull cable",
"door handle mounting plate",
"front bumper reinforcement beam",
"rear bumper reinforcement beam",
"front bumper absorber foam",
"rear bumper absorber foam",
"bumper corner extension",
"bumper center garnish",
"bumper lower spoiler lip",
"bumper air intake grille",
"bumper mounting support rail",
"bumper reinforcement bracket",
"bumper decorative trim",
"bumper corner protector",
"bumper impact support",
"bumper side bracket",
"bumper energy absorber",
"bumper support crossbar",
"bumper grille insert",
"bumper trim molding",
"bumper mounting spacer",
"bumper protective guard",
"projector headlight assembly",
"led headlamp module",
"halogen headlamp assembly",
"headlight leveling motor",
"headlight mounting bracket",
"headlight protective lens",
"headlight housing shell",
"headlight reflector bowl",
"headlight wiring connector",
"headlight aiming adjuster",
"headlight bulb retaining clip",
"headlight ballast module",
"headlight dust cover cap",
"headlight heat sink module",
"headlight lens seal gasket",
"headlight mounting tab",
"headlight protective guard",
"headlight trim bezel",
"headlight harness connector",
"headlight ventilation cap",
"led tail lamp assembly",
"rear combination lamp unit",
"tail light lens cover",
"tail light housing shell",
"tail light mounting bracket",
"tail light wiring connector",
"tail light reflector module",
"tail light bulb socket",
"tail light protective cover",
"tail light trim bezel",
"tail light sealing gasket",
"tail light mounting tab",
"tail light harness connector",
"tail light signal diffuser",
"tail light reinforcement plate",
"tail light retaining screw",
"tail light mounting clip",
"tail light frame bracket",
"tail light lens protector",
"tail light ventilation cap",
"led tail lamp assembly",
"rear combination lamp unit",
"tail light lens cover",
"tail light housing shell",
"tail light mounting bracket",
"tail light wiring connector",
"tail light reflector module",
"tail light bulb socket",
"tail light protective cover",
"tail light trim bezel",
"tail light sealing gasket",
"tail light mounting tab",
"tail light harness connector",
"tail light signal diffuser",
"tail light reinforcement plate",
"tail light retaining screw",
"tail light mounting clip",
"tail light frame bracket",
"tail light lens protector",
"tail light ventilation cap",
"waterproof car body cover",
"dustproof vehicle cover",
"all weather car cover",
"uv resistant car cover",
"outdoor protective car cover",
"indoor storage car cover",
"elastic hem car cover",
"windproof strap car cover",
"full body vehicle cover",
"sedan car protective cover",
"suv car protective cover",
"hatchback car protective cover",
"premium breathable car cover",
"rainproof vehicle cover",
"scratch resistant car cover",
"silver reflective car cover",
"multi layer car cover",
"heat resistant car cover",
"storm protection car cover",
"heavy duty car cover",
  "stainless steel exhaust pipe",
"sport exhaust muffler",
"rear exhaust silencer",
"exhaust mid pipe",
"exhaust downpipe",
"exhaust catalytic shield",
"exhaust flange gasket ring",
"exhaust pipe mounting clamp",
"exhaust pipe hanger bracket",
"exhaust rubber isolator",
"exhaust pipe flex joint",
"exhaust manifold heat shield",
"exhaust pipe mounting bracket",
"exhaust tip chrome finish",
"exhaust pipe connector sleeve",
"exhaust resonator chamber",
"exhaust pipe support bracket",
"exhaust pipe retaining clamp",
"exhaust mounting rubber strap",
"exhaust hanger support rod",
]

module.exports = function detectAutoQuery(text){

for(const p of parts){

if(text.includes(p)){
return true
}

}

return false

}
